# Generated by Django 5.0.3 on 2024-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
